### ISSUE TITLE
I would love to learn from you.

### ISSUE THREAD

**Issue by RafaelZasas** [karmanyaahm/google_classroom_discord_feed#2]
I am doing something very similar for work and would love to have a chat without about how you implemented a few things. Namely, Authentication (I see you store the tokens on each user's db entry) and PubSub (I'm new to this and need help).

Please let me know if this would be possible.

**Comment by karmanyaahm** [comment]
Unfortunately, this project is not finished, and I stopped working on it a while ago due to no longer using google classroom.

However, I'll email you on the email mentioned on your website if you want to discuss design ideas.
